---

- fail: msg="Variable share_path is required"
  when: share_path is not defined

- name: get share dataset
  shell: zfs list | grep '\s{{ share_path }}$' | cut -d ' ' -f1
  register: share_dataset
  changed_when: False

- name: Include zfs_share vars
  include_vars:
    file: zfs_share.yml

- fail: msg="Variable zshares is required"
  when: zshares is not defined

- name: set share zfs properties
  zfs:
    name: "{{ share_dataset.stdout }}"
    state: present
    extra_zfs_properties:
      setuid: off
      compression: "lz4"
      sharenfs: off
      sharesmb: off
  when: share_dataset.stdout != ""

- name: set share directory attributes
  file:
    path: "{{ share_path }}"
    owner: root
    group: share
    mode: '0755'
  when: share_dataset.stdout != ""

- name: create share datasets
  zfs:
    name: "{{ share_dataset.stdout }}/{{ dataset.name }}"
    state: present
    extra_zfs_properties: "{{ dataset.properties }}"
  with_items: "{{ zshares }}"
  loop_control:
    loop_var: dataset
  when: share_dataset.stdout != ""

- name: set share datasets rights
  file:
    path: "{{ share_path }}/{{ dataset.name }}"
    owner: "{{ dataset.owner }}"
    group: "{{ dataset.group }}"
    mode: "{{ dataset.mode }}"
  with_items: "{{ zshares }}"
  loop_control:
    loop_var: dataset
  when: share_dataset.stdout != ""
